---
- name: samba is installed
  apt: name=samba state=latest install_recommends=no
  with_items:
    - samba
    - smbclient
    - libpam-smbpass

- name: samba share groups
  group: name={{samba.group}} state=present

- name: create shared folders
  file: path="{{item.path}}" state=directory mode=775 owner=root group={{samba.group}}
  with_items: samba.shares

- name: samba config
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - restart smbd
    - restart nmbd

- name: start smbd
  service: name=smbd state=started enabled=yes

- name: start nmbd
  service: name=nmbd state=started enabled=yes

- name: Set firewall rule
  ufw: rule=allow name=samba
