- name: Which kernel is installed?
  shell: uname -a | cut -d " " -f 3
  changed_when: False
  register: current_kernel

- name: download kernel
  get_url: url=http://kernel.ubuntu.com/~kernel-ppa/mainline/{{kernel_name}}/{{item}}
           dest=/tmp/{{item}}
  with_items: kernel_debs
  when: 'current_kernel.stdout not in "{{kernel_version}}"'
  register: download

- name: install kernel (1)
  apt: deb={{item}} state=installed
  # we need to specify the full path, see bug reports:
  # https://github.com/ansible/ansible/issues/8314
  # https://github.com/ansible/ansible/issues/9235
  with_items:
    - /tmp/linux-headers-3.16.6-031606_3.16.6-031606.201410150635_all.deb
  when: download|changed

- name: install kernel (2)
  apt: deb={{item}} state=installed
  with_items:
    - /tmp/linux-headers-3.16.6-031606-generic_3.16.6-031606.201410150635_amd64.deb
    - /tmp/linux-image-3.16.6-031606-generic_3.16.6-031606.201410150635_amd64.deb
  when: download|changed

- name: enable ASPM and ACPI (kernel parameter)
  lineinfile: regexp="^GRUB_CMDLINE_LINUX_DEFAULT"
              line="GRUB_CMDLINE_LINUX_DEFAULT=\"quiet nosplash acpi=force pcie_aspm=force nmi_watchdog=0\""
              dest=/etc/default/grub
              state=present
  register: kernel_parameters

- name: update grub config
  command: /usr/sbin/update-grub
  when: kernel_parameters|changed

- name: restart machine
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true
  when: download|changed or kernel_parameters|changed

- name: waiting for server to come back
  sudo: false
  local_action: wait_for host={{ansible_ssh_host}}
                port={{ansible_ssh_port}} state=started
  when: download|changed or kernel_parameters|changed
