---
- name: Install necessities and nice-to-haves
  apt: pkg={{item}} state=installed install_recommends=no
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - unzip
    - mosh
    - git
    - gdisk

- name: set hostname
  template: src=hostname.j2 dest=/etc/hostname

- name: set default shell for useradd
  lineinfile: dest=/etc/default/useradd regexp="^SHELL=" line="SHELL=/bin/bash"

- name: enable multiverse repository
  apt_repository: repo="{{item}}" update_cache=yes state=present
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu trusty multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu trusty multiverse"
    - "deb http://archive.ubuntu.com/ubuntu trusty-updates multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu trusty-updates multiverse"

- name: enable backports repository
  apt_repository: repo="{{item}}" update_cache=yes state=present
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"


- include: users.yml tags=users

- include: kernel.yml tags=kernel
  vars:
    kernel_version: 3.16.6-031606-generic
    kernel_name: v3.16.6-utopic
    kernel_debs:
      - linux-image-3.16.6-031606-generic_3.16.6-031606.201410150635_amd64.deb
      - linux-headers-3.16.6-031606_3.16.6-031606.201410150635_all.deb
      - linux-headers-3.16.6-031606-generic_3.16.6-031606.201410150635_amd64.deb

- include: ufw.yml tags=ufw
- include: security.yml tags=security
- include: ntp.yml tags=ntp
- include: ssmtp.yml tags=ssmtp
