---
- name: Install necessities and nice-to-haves
  apt: pkg={{item}} state=installed install_recommends=no
  with_items:
    - sudo
    - vim
    - htop
    - iftop
    - iotop
    - unzip
    - mosh
    - git
    - gdisk

- name: set hostname
  template: src=hostname.j2 dest=/etc/hostname

- name: set default shell for useradd
  lineinfile: dest=/etc/default/useradd regexp="^SHELL=" line="SHELL=/bin/bash"

- name: add wheezy backports (deb)
  apt_repository: repo="deb http://ftp.debian.org/debian/ wheezy-backports main contrib non-free" update_cache=yes state=present
  register: repo_added

- name: add wheezy backports (deb-src)
  apt_repository: repo="deb-src http://ftp.debian.org/debian/ wheezy-backports main contrib non-free" update_cache=yes state=present

- name: update repo cache
  apt: update_cache=yes
  when: repo_added|changed

- include: users.yml tags=users
- include: ufw.yml tags=ufw
- include: security.yml tags=security
- include: ntp.yml tags=ntp
- include: ssmtp.yml tags=ssmtp
