---
- name: enable multiverse repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu bionic multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu bionic multiverse"
    - "deb http://archive.ubuntu.com/ubuntu bionic-updates multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu bionic-updates multiverse"

- name: enable backports repository
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse"
    - "deb-src http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse"

- name: Install necessities and nice-to-haves
  apt:
    install_recommends: no
    pkg:
      - apt-transport-https
      - ca-certificates
      - gdisk
      - git
      - htop
      - iftop
      - iotop
      - mosh
      - p7zip
      - software-properties-common
      - sudo
      - unrar
      - unzip
      - vim
      - zsh
    state: present

- name: set hostname
  template:
    dest: /etc/hostname
    src: hostname.j2

- name: set default shell for useradd
  lineinfile:
    dest: /etc/default/useradd
    line: "SHELL: /bin/zsh"
    regexp: "^SHELL: "


- name: set grub timeout to 3 in /etc/default/grub
  replace:
    dest: /etc/default/grub
    regexp: "^(GRUB_TIMEOUT)=[0-9]*$"
    replace: "\\1=3"
  notify: update grub


- name: update kernel parameters
  lineinfile:
    dest: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT="
    line: "GRUB_CMDLINE_LINUX_DEFAULT=\"intel_iommu=on\""
  notify: update grub

- include: users.yml tags=users
- include: ufw.yml tags=ufw
- include: security.yml tags=security
- include: ntp.yml tags=ntp
- include: network.yml tags=network
- include: ssmtp.yml tags=ssmtp
