---
- name: Install security-related packages
  apt:
    install_recommends: no
    pkg:
      - fail2ban
      - rkhunter
      - lynis
    state: present

- name: start fail2ban
  service:
    enabled: yes
    name: fail2ban
    state: started

# - name: Copy fail2ban configuration into place
#   template: src=etc_fail2ban_jail.local.j2 dest=/etc/fail2ban/jail.local
#   notify: restart fail2ban

- name: Update sshd config to disallow root logins
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PermitRootLogin no"
    regexp: "^PermitRootLogin"
    state: present
  notify: restart ssh

- name: Update sshd to disallow password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
    regexp: "^PasswordAuthentication"
    state: present
  notify: restart ssh
