---
- name: Install ufw
  apt:
    pkg: ufw
    state: present

- name: Deny everything and enable UFW
  ufw:
    direction: incoming
    policy: deny
    state: enabled

- name: Set firewall rule for DNS
  ufw:
    port: domain
    rule: allow

- name: Set firewall rules
  ufw:
    name: "{{ item }}"
    rule: allow 
  with_items:
    - OpenSSH
    - mosh
