---
- name: Install ufw
  apt: pkg=ufw state=present

- name: Deny everything and enable UFW
  ufw: state=enabled policy=deny

- name: Set firewall rule for DNS
  ufw: rule=allow port=domain

- name: Configure mosh
  copy: src=mosh.ufw dest=/etc/ufw/applications.d/mosh owner=root mode=0644

- name: Set firewall rules
  ufw: rule=allow name={{item}}
  with_items:
    - OpenSSH
    - mosh
