---
- name: Add ssh users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    update_password: on_create
  with_items: "{{ users }}"

- name: add users group
  group:
    name: users
    state: present

- name: Add users to 'users' group
  user:
    append: yes
    groups: users
    name: "{{ item.name }}"
  with_items: "{{ users }}"

- name: add public keys to authorized_keys files
  authorized_key:
    key: "{{ item.key }}"
    user: "{{ item.name }}"
  when: item.key is defined
  with_items: "{{ users }}"

- name: add sudo permissions
  user:
    append: yes
    groups: sudo
    name: "{{ item.name }}"
  when: item.admin is defined and item.admin
  with_items: "{{ users }}"
