---
- name: Install required packages
  apt: pkg=aufs-tools state=installed install_recommends=no

- name: ensure directories to merge do exists
  file: path={{item.1}} state=directory
  with_subelements:
    - union_mount
    - dirs

- name: create mount points for union mounts
  file: path={{item.mount}} recurse=yes state=directory
  with_items: union_mount

- name: mount unification of directories
  mount: name={{item.dest}} src=none fstype=aufs opts=br={{item.dirs|join("=rw:")}}=rw,create=mfs,cpup=bup,auto state=mounted
  with_items: union_mount
