---
- name: ensure groups exist
  group:
    name: "{{ item.group }}"
    state: present
  with_items: "{{ directories }}"

- name: create directories and set permissions
  file:
    group: "{{ item.group }}"
    mode: "{{ item.permission }}"
    owner: "{{ item.owner }}"
    path: "{{ item.path }}"
    state: directory
  with_items: "{{ directories }}"
