---
- name: ensure groups exist
  group: name={{item.group}} state=present
  with_items: directories

- name: create directories and set permissions
  file: path={{item.path}} state=directory
        owner={{item.owner}} group={{item.group}}
        mode={{item.permission}}
  with_items: directories
