---
- name: create mount points
  file:
    path: "{{ item.mount }}"
    state: directory
  with_items: "{{ harddisks }}"

- name: mount disks
  mount:
    boot: yes
    fstype: "{{ item.fstype }}"
    opts: "{{ item.opts }}"
    path: "{{ item.dest }}"
    src: "UUID={{ item.uuid }}"
    state: mounted
  with_items: "{{ harddisks }}"
