---
- name: Install or update required packages
  apt: pkg={{item}} default_release=wheezy-backports state=latest install_recommends=no
  with_items:
    - btrfs-tools

- include: fstab.yml tags=fstab
- include: aufs.yml tags=aufs
