---
- name: Install or update required packages
  apt: pkg={{item}} default_release=wheezy-backports state=latest install_recommends=no
  with_items:
    - btrfs-tools

- name: install latest kernel from backports (for btrfs)
  apt: pkg={{item}} default_release=wheezy-backports state=latest install_recommends=no
  with_items:
    - linux-headers-amd64
    - linux-image-amd64
  register: kernel_updated

- name: restart machine
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true
  when: kernel_updated|changed

- name: waiting for server to come back
  local_action: wait_for host={{inventory_hostname}}
                port={{ansible_ssh_port}} state=started
  sudo: false
  when: kernel_updated|changed

- include: fstab.yml tags=fstab
- include: aufs.yml tags=aufs
