---
- name: install drivers
  apt: name={{item}} state=installed install_recommends=no
  with_items:
    - linux-firmware-nonfree
    - amd64-microcode

- name: install acpi
  apt: name={{item}} state=installed install_recommends=no
  with_items:
      - acpi
      - acpid
      - acpi-support

- name: start acpid
  service: name=acpid state=started enabled=yes

- name: install powermanagement udev rule
  copy: src=90-local-n54l.rules dest=/etc/udev/rules.d/90-local-n54l.rules
  register: udev_rules

- name: reload udev rules
  command: udevadm control --reload-rules
  when: udev_rules|changed

- include: hdparm.yml tags=hdparm
- include: powernap.yml tags=powernap
