---
- name: install drivers and utilities
  apt:
    install_recommends: no
    name:
      - intel-microcode
      - linux-firmware
      - powertop
    state: present

- name: install acpi
  apt:
    install_recommends: no
    name:
      - acpi
      - acpid
      - acpi-support
    state: present

- name: start acpid
  service:
    enabled: yes
    name: acpid
    state: started

- include: hdparm.yml tags=hdparm
- include: nvidia.yml tags=nvidia
- include: tuned.yml tags=tuned
