---
- name: powernap | install
  apt: name=powernap state=installed force=yes

- name: powernap | enable service
  service: name=powernap enabled=yes state=running

- name: powernap | config
  template: src=config.j2 dest=/etc/powernap/config
  notify: restart powernap
